/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomStylesRouteImport } from './routes/custom-styles'
import { Route as LimitsRouteImport } from './routes/limits'
import { Route as MoveHandleRouteImport } from './routes/move-handle'
import { Route as SinglePolygonRouteImport } from './routes/single-polygon'
import { Route as SnapRouteImport } from './routes/snap'
import { Route as UndoRouteImport } from './routes/undo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomStylesRoute = CustomStylesRouteImport.update({
  id: '/custom-styles',
  path: '/custom-styles',
  getParentRoute: () => rootRouteImport,
} as any)
const LimitsRoute = LimitsRouteImport.update({
  id: '/limits',
  path: '/limits',
  getParentRoute: () => rootRouteImport,
} as any)
const MoveHandleRoute = MoveHandleRouteImport.update({
  id: '/move-handle',
  path: '/move-handle',
  getParentRoute: () => rootRouteImport,
} as any)
const SinglePolygonRoute = SinglePolygonRouteImport.update({
  id: '/single-polygon',
  path: '/single-polygon',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapRoute = SnapRouteImport.update({
  id: '/snap',
  path: '/snap',
  getParentRoute: () => rootRouteImport,
} as any)
const UndoRoute = UndoRouteImport.update({
  id: '/undo',
  path: '/undo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/custom-styles': typeof CustomStylesRoute
  '/limits': typeof LimitsRoute
  '/move-handle': typeof MoveHandleRoute
  '/single-polygon': typeof SinglePolygonRoute
  '/snap': typeof SnapRoute
  '/undo': typeof UndoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom-styles': typeof CustomStylesRoute
  '/limits': typeof LimitsRoute
  '/move-handle': typeof MoveHandleRoute
  '/single-polygon': typeof SinglePolygonRoute
  '/snap': typeof SnapRoute
  '/undo': typeof UndoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/custom-styles': typeof CustomStylesRoute
  '/limits': typeof LimitsRoute
  '/move-handle': typeof MoveHandleRoute
  '/single-polygon': typeof SinglePolygonRoute
  '/snap': typeof SnapRoute
  '/undo': typeof UndoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/custom-styles'
    | '/limits'
    | '/move-handle'
    | '/single-polygon'
    | '/snap'
    | '/undo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/custom-styles'
    | '/limits'
    | '/move-handle'
    | '/single-polygon'
    | '/snap'
    | '/undo'
  id:
    | '__root__'
    | '/'
    | '/custom-styles'
    | '/limits'
    | '/move-handle'
    | '/single-polygon'
    | '/snap'
    | '/undo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomStylesRoute: typeof CustomStylesRoute
  LimitsRoute: typeof LimitsRoute
  MoveHandleRoute: typeof MoveHandleRoute
  SinglePolygonRoute: typeof SinglePolygonRoute
  SnapRoute: typeof SnapRoute
  UndoRoute: typeof UndoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-styles': {
      id: '/custom-styles'
      path: '/custom-styles'
      fullPath: '/custom-styles'
      preLoaderRoute: typeof CustomStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limits': {
      id: '/limits'
      path: '/limits'
      fullPath: '/limits'
      preLoaderRoute: typeof LimitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/move-handle': {
      id: '/move-handle'
      path: '/move-handle'
      fullPath: '/move-handle'
      preLoaderRoute: typeof MoveHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/single-polygon': {
      id: '/single-polygon'
      path: '/single-polygon'
      fullPath: '/single-polygon'
      preLoaderRoute: typeof SinglePolygonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snap': {
      id: '/snap'
      path: '/snap'
      fullPath: '/snap'
      preLoaderRoute: typeof SnapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/undo': {
      id: '/undo'
      path: '/undo'
      fullPath: '/undo'
      preLoaderRoute: typeof UndoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomStylesRoute: CustomStylesRoute,
  LimitsRoute: LimitsRoute,
  MoveHandleRoute: MoveHandleRoute,
  SinglePolygonRoute: SinglePolygonRoute,
  SnapRoute: SnapRoute,
  UndoRoute: UndoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
